apiVersion: honey.shareed2k.io/v1alpha1
kind: MacroSet
metadata:
  name: ops-macros
spec:
  macros:
    open-admin-app:
      kind: app
      app: eu2-kafka-metrics
      openBrowser: true

    tunnel-postgres:
      kind: tunnel
      app: stg2-postgres
