// Code generated by swaggo/swag. DO NOT EDIT.

package swaggerdocs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "honey"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/backends": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "List configured backends",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hostapi.ListBackendsOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/config": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/yaml"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get honey YAML config",
                "responses": {
                    "200": {
                        "description": "YAML document",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Replace honey YAML config",
                "parameters": [
                    {
                        "description": "Full YAML document (Content-Type application/yaml or text/plain)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/config/backends": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "List backends from config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.Backends"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/config/backends/{kind}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Append backend entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "backend kind (gcp, aws, kubernetes, consul, proxmox, local)",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Backend entry JSON (shape depends on kind path param)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.ConfigBackendEntryBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/config/backends/{kind}/{index}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Replace backend entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "backend kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0-based index in that kind's list",
                        "name": "index",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Backend entry JSON (shape depends on kind path param)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.ConfigBackendEntryBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Delete backend entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "backend kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0-based index",
                        "name": "index",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/config/schema": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Config JSON Schema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.ConfigSchemaResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/cue-exec": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "CUE recipe dry-run or execute",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "set to 1 for NDJSON streaming when execute=true",
                        "name": "stream",
                        "in": "query"
                    },
                    {
                        "description": "cue-exec request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.CueExecRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "host results when execute=true and stream is not set",
                        "schema": {
                            "$ref": "#/definitions/webserver.CueExecExecuteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/exec": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exec"
                ],
                "summary": "Parallel remote exec",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "set to 1 for NDJSON streaming",
                        "name": "stream",
                        "in": "query"
                    },
                    {
                        "description": "remote exec request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.ExecRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JSON body; NDJSON stream of HostExecResultDoc when stream=1",
                        "schema": {
                            "$ref": "#/definitions/webserver.ExecResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/files/agent-transfer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Agent-based cloud transfer",
                "parameters": [
                    {
                        "description": "agent transfer request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.FilesAgentTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.FilesAgentTransferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/files/copy": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Copy file local/remote",
                "parameters": [
                    {
                        "description": "copy between local and remote paths",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.FilesCopyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.FilesCopyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/files/local/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "List local directory",
                "parameters": [
                    {
                        "description": "path relative to browser root",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.FilesLocalListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.FilesLocalListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/files/remote/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "List remote directory",
                "parameters": [
                    {
                        "description": "ssh_user, record, path",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.FilesRemoteListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.FilesRemoteListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/host-ports": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "List listening ports on a host",
                "parameters": [
                    {
                        "description": "ssh_user and host record",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.HostPortsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.HostPortsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/meta": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Server metadata",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.MetaResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/providers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "List search provider IDs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.ProvidersResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pve-qemu-vnc-offer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxmox"
                ],
                "summary": "Proxmox QEMU VNC offer",
                "parameters": [
                    {
                        "description": "record for a QEMU VM on Proxmox",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.PveQemuVncOfferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.PveQemuVncOfferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/recipes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "List recipe files",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.RecipesListResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recipes/assist": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Recipe AI assist",
                "parameters": [
                    {
                        "description": "recipe assist request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.RecipesAssistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.RecipesAssistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/recipes/graph-plan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Build graph recipe plan",
                "parameters": [
                    {
                        "description": "path or recipe_content",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.GraphPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.RecipeGraphPlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/recipes/parse": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Parse recipe file to JSON",
                "parameters": [
                    {
                        "description": "absolute recipe file path",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.RecipesParseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.RecipesParseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/recipes/recent-runs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Recent recipe runs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "max entries (default 20, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.RecentRunsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recipes/validate-content": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Validate recipe JSON",
                "parameters": [
                    {
                        "description": "recipe object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.ValidateContentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.ValidateContentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/webserver.ValidateContentResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recipes/view": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Read recipe file",
                "parameters": [
                    {
                        "description": "absolute or resolved recipe path",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.RecipeViewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.RecipeViewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/recordings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recordings"
                ],
                "summary": "List session recordings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter by provider",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by host name",
                        "name": "host_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by host IP",
                        "name": "host_ip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.RecordingsListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/recordings/play": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recordings"
                ],
                "summary": "Load recording events",
                "parameters": [
                    {
                        "description": "recording file name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.RecordingsPlayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.RecordingsPlayResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/search": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search hosts",
                "parameters": [
                    {
                        "description": "search request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hostapi.SearchHostsInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hostapi.SearchHostsOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/terminal-assist": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assist"
                ],
                "summary": "Terminal AI assist",
                "parameters": [
                    {
                        "description": "scrollback, user_prompt, model, max_lines",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.TerminalAssistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.TerminalAssistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/terminal-assist/models": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assist"
                ],
                "summary": "Terminal assist models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.TerminalAssistModelsResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/tunnels": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnels"
                ],
                "summary": "List tunnels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.TunnelsListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnels"
                ],
                "summary": "Start tunnel",
                "parameters": [
                    {
                        "description": "ssh_user, record, mapping (e.g. 8080:localhost:8080)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webserver.StartTunnelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.TunnelStartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/tunnels/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnels"
                ],
                "summary": "Stop tunnel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tunnel id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.TunnelDeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/tunnels/{id}/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnels"
                ],
                "summary": "Tunnel logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tunnel id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webserver.TunnelLogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload file to remote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JSON UploadRequestMeta: ssh_user, remote_path, record (hosts.Record)",
                        "name": "meta",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File contents",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "set to 1 for NDJSON streaming response",
                        "name": "stream",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JSON body; NDJSON progress lines when stream=1",
                        "schema": {
                            "$ref": "#/definitions/webserver.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.AWSBackend": {
            "type": "object",
            "required": [
                "name",
                "profile"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "config.BackendRow": {
            "type": "object",
            "properties": {
                "hint": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "config.Backends": {
            "type": "object",
            "properties": {
                "aws": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.AWSBackend"
                    }
                },
                "consul": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.ConsulBackend"
                    }
                },
                "gcp": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.GCPBackend"
                    }
                },
                "kubernetes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.KubernetesBackend"
                    }
                },
                "local": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.LocalBackend"
                    }
                },
                "proxmox": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.ProxmoxBackend"
                    }
                }
            }
        },
        "config.ConsulBackend": {
            "type": "object",
            "required": [
                "addr",
                "name"
            ],
            "properties": {
                "addr": {
                    "type": "string"
                },
                "datacenter": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "config.GCPBackend": {
            "type": "object",
            "required": [
                "name",
                "project"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "project": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "config.KubernetesBackend": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "context": {
                    "type": "string"
                },
                "debug_image": {
                    "type": "string"
                },
                "kubeconfig": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "config.LocalBackend": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "hosts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.LocalHost"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "config.LocalHost": {
            "type": "object",
            "required": [
                "name",
                "primary_ip"
            ],
            "properties": {
                "extra_ips": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "primary_ip": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "config.ProxmoxBackend": {
            "type": "object",
            "required": [
                "name",
                "url"
            ],
            "properties": {
                "exec_mode": {
                    "description": "ExecMode: ssh (default) = guest SSH for commands/SFTP/tunnels; pve = QEMU commands via guest agent API, LXC commands/SFTP over guest SSH (PVE has no LXC REST exec; web UI LXC console uses termproxy when token_id is set);\nhybrid = QEMU via guest agent + SSH for files; LXC uses guest SSH for commands and files.",
                    "type": "string"
                },
                "insecure": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                },
                "token_secret": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "hostapi.ListBackendsOutput": {
            "type": "object",
            "properties": {
                "backends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.BackendRow"
                    }
                },
                "config_path": {
                    "type": "string"
                }
            }
        },
        "hostapi.SearchHostsInput": {
            "type": "object",
            "properties": {
                "aws_profile": {
                    "type": "string"
                },
                "aws_region": {
                    "type": "string"
                },
                "backends": {
                    "type": "string"
                },
                "cache_dir": {
                    "type": "string"
                },
                "cache_ttl": {
                    "type": "string"
                },
                "config_path": {
                    "type": "string"
                },
                "consul_addr": {
                    "type": "string"
                },
                "consul_datacenter": {
                    "type": "string"
                },
                "consul_token": {
                    "type": "string"
                },
                "gcp_project": {
                    "type": "string"
                },
                "gcp_zone": {
                    "type": "string"
                },
                "k8s_debug_image": {
                    "type": "string"
                },
                "k8s_mode": {
                    "type": "string"
                },
                "kube_context": {
                    "type": "string"
                },
                "kubeconfig": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "name_regex": {
                    "type": "string"
                },
                "no_cache": {
                    "type": "boolean"
                },
                "providers": {
                    "type": "string"
                },
                "proxmox_insecure": {
                    "type": "boolean"
                },
                "proxmox_password": {
                    "type": "string"
                },
                "proxmox_token_id": {
                    "type": "string"
                },
                "proxmox_token_secret": {
                    "type": "string"
                },
                "proxmox_url": {
                    "type": "string"
                },
                "proxmox_user": {
                    "type": "string"
                },
                "refresh": {
                    "type": "boolean"
                }
            }
        },
        "hostapi.SearchHostsOutput": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hosts.Record"
                    }
                }
            }
        },
        "hosts.Record": {
            "type": "object",
            "properties": {
                "extra_ips": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "primary_ip": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "recordings.Event": {
            "type": "object",
            "properties": {
                "cols": {
                    "type": "integer"
                },
                "data_b64": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rows": {
                    "type": "integer"
                },
                "time_ms": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "ui.AgentCloudBackend": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "ui.AgentTransferEvent": {
            "type": "object",
            "properties": {
                "attempt": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "ui.CloudBackendRef": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "ui.HostExecResult": {
            "type": "object",
            "properties": {
                "errMsg": {
                    "description": "transport / spawn failure (not remote stderr)",
                    "type": "string"
                },
                "exitCode": {
                    "type": "integer"
                },
                "hookOutput": {
                    "description": "captured stdout+stderr from the hook (local or remote)",
                    "type": "string"
                },
                "hookPhase": {
                    "description": "HookPhase / HookOutput are set when a CUE step hook ran after the main result (command/script only).",
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "skipped": {
                    "description": "when CEL was false; no SSH/SFTP ran",
                    "type": "boolean"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "ui.LocalFileEntry": {
            "type": "object",
            "properties": {
                "is_dir": {
                    "type": "boolean"
                },
                "mode": {
                    "type": "string"
                },
                "modified_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "ui.RemoteFileEntry": {
            "type": "object",
            "properties": {
                "is_dir": {
                    "type": "boolean"
                },
                "mode": {
                    "type": "string"
                },
                "modified_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "webserver.ActiveTunnel": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mapping": {
                    "type": "string"
                },
                "record_key": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                }
            }
        },
        "webserver.ConfigBackendEntryBody": {
            "type": "object",
            "additionalProperties": true
        },
        "webserver.ConfigSchemaResponse": {
            "type": "object",
            "properties": {
                "json_schema": {
                    "type": "object",
                    "additionalProperties": true
                },
                "ui_schema": {}
            }
        },
        "webserver.CueExecDryRunResponse": {
            "type": "object",
            "properties": {
                "plan": {
                    "type": "string"
                }
            }
        },
        "webserver.CueExecExecuteResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ui.HostExecResult"
                    }
                }
            }
        },
        "webserver.CueExecRequest": {
            "type": "object",
            "properties": {
                "env": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "execute": {
                    "type": "boolean"
                },
                "recipe_content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "recipe_path": {
                    "type": "string"
                },
                "record_session": {
                    "type": "boolean"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hosts.Record"
                    }
                },
                "ssh_user": {
                    "type": "string"
                }
            }
        },
        "webserver.ExecRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "record_session": {
                    "type": "boolean"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hosts.Record"
                    }
                },
                "ssh_user": {
                    "type": "string"
                }
            }
        },
        "webserver.ExecResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ui.HostExecResult"
                    }
                }
            }
        },
        "webserver.FilesAgentTransferRequest": {
            "type": "object",
            "properties": {
                "agent_local_path": {
                    "type": "string"
                },
                "agent_remote_dir": {
                    "type": "string"
                },
                "cloud": {
                    "$ref": "#/definitions/ui.AgentCloudBackend"
                },
                "cloud_backend_ref": {
                    "$ref": "#/definitions/ui.CloudBackendRef"
                },
                "credentials": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "dest_path": {
                    "type": "string"
                },
                "dest_record": {
                    "$ref": "#/definitions/hosts.Record"
                },
                "keep_object": {
                    "type": "boolean"
                },
                "max_retries": {
                    "type": "integer"
                },
                "source_path": {
                    "type": "string"
                },
                "source_record": {
                    "$ref": "#/definitions/hosts.Record"
                },
                "ssh_user": {
                    "type": "string"
                }
            }
        },
        "webserver.FilesAgentTransferResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ui.AgentTransferEvent"
                    }
                }
            }
        },
        "webserver.FilesCopyRequest": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string"
                },
                "local_path": {
                    "type": "string"
                },
                "record": {
                    "$ref": "#/definitions/hosts.Record"
                },
                "remote_path": {
                    "type": "string"
                },
                "ssh_user": {
                    "type": "string"
                }
            }
        },
        "webserver.FilesCopyResponse": {
            "type": "object",
            "properties": {
                "local": {
                    "type": "string"
                },
                "remote": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "webserver.FilesLocalListRequest": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                }
            }
        },
        "webserver.FilesLocalListResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ui.LocalFileEntry"
                    }
                },
                "path": {
                    "type": "string"
                },
                "root": {
                    "type": "string"
                }
            }
        },
        "webserver.FilesRemoteListRequest": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "record": {
                    "$ref": "#/definitions/hosts.Record"
                },
                "ssh_user": {
                    "type": "string"
                }
            }
        },
        "webserver.FilesRemoteListResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ui.RemoteFileEntry"
                    }
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "webserver.GraphPlanEdgeDoc": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "webserver.GraphPlanNodeDoc": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "kind": {
                    "type": "string"
                },
                "kv_tunnel": {
                    "type": "boolean"
                },
                "preview": {
                    "type": "string"
                },
                "wave": {
                    "type": "integer"
                },
                "when": {
                    "type": "string"
                }
            }
        },
        "webserver.GraphPlanRequest": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "recipe_content": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "webserver.HostPortsRequest": {
            "type": "object",
            "properties": {
                "record": {
                    "$ref": "#/definitions/hosts.Record"
                },
                "ssh_user": {
                    "type": "string"
                }
            }
        },
        "webserver.HostPortsResponse": {
            "type": "object",
            "properties": {
                "ports": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "webserver.MetaResponse": {
            "type": "object",
            "properties": {
                "commit": {
                    "type": "string"
                },
                "config_path": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "session_recording_available": {
                    "type": "boolean"
                },
                "terminal_assist_available": {
                    "type": "boolean"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "webserver.ProvidersResponse": {
            "type": "object",
            "properties": {
                "providers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "webserver.PveQemuVncOfferRequest": {
            "type": "object",
            "properties": {
                "record": {
                    "$ref": "#/definitions/hosts.Record"
                }
            }
        },
        "webserver.PveQemuVncOfferResponse": {
            "type": "object",
            "properties": {
                "session_id": {
                    "type": "string"
                },
                "vnc_password": {
                    "type": "string"
                }
            }
        },
        "webserver.RecentRunEntry": {
            "type": "object",
            "properties": {
                "edited": {
                    "type": "boolean"
                },
                "host_count": {
                    "type": "integer"
                },
                "recipe_content_hash": {
                    "type": "string"
                },
                "recipe_name": {
                    "type": "string"
                },
                "recipe_path": {
                    "type": "string"
                },
                "recording_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                }
            }
        },
        "webserver.RecentRunsResponse": {
            "type": "object",
            "properties": {
                "runs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webserver.RecentRunEntry"
                    }
                }
            }
        },
        "webserver.RecipeGraphPlanResponse": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webserver.GraphPlanEdgeDoc"
                    }
                },
                "mermaid": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webserver.GraphPlanNodeDoc"
                    }
                },
                "type": {
                    "type": "string"
                },
                "waves": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/webserver.GraphPlanNodeDoc"
                        }
                    }
                }
            }
        },
        "webserver.RecipeListEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "webserver.RecipeViewRequest": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                }
            }
        },
        "webserver.RecipeViewResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "webserver.RecipesAssistRequest": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "recipe_path": {
                    "type": "string"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hosts.Record"
                    }
                },
                "ssh_user": {
                    "type": "string"
                },
                "user_prompt": {
                    "type": "string"
                }
            }
        },
        "webserver.RecipesAssistResponse": {
            "type": "object",
            "properties": {
                "reply": {
                    "type": "string"
                }
            }
        },
        "webserver.RecipesListResponse": {
            "type": "object",
            "properties": {
                "recipes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webserver.RecipeListEntry"
                    }
                }
            }
        },
        "webserver.RecipesParseRequest": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                }
            }
        },
        "webserver.RecipesParseResponse": {
            "type": "object",
            "properties": {
                "recipe": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "webserver.RecordingListEntry": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "host_ip": {
                    "type": "string"
                },
                "host_name": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "modified_unix_ms": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "trigger": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "webserver.RecordingsListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webserver.RecordingListEntry"
                    }
                }
            }
        },
        "webserver.RecordingsPlayRequest": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                }
            }
        },
        "webserver.RecordingsPlayResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recordings.Event"
                    }
                },
                "file_name": {
                    "type": "string"
                }
            }
        },
        "webserver.ResolvedStepSummary": {
            "type": "object",
            "properties": {
                "depends": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "kind": {
                    "type": "string"
                },
                "preview": {
                    "type": "string"
                },
                "run_as": {
                    "type": "string"
                },
                "wave": {
                    "type": "integer"
                },
                "when": {
                    "type": "string"
                }
            }
        },
        "webserver.StartTunnelRequest": {
            "type": "object",
            "properties": {
                "mapping": {
                    "type": "string"
                },
                "record": {
                    "$ref": "#/definitions/hosts.Record"
                },
                "ssh_user": {
                    "type": "string"
                }
            }
        },
        "webserver.StatusResponse": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "webserver.TerminalAssistModelsResponse": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "webserver.TerminalAssistRequest": {
            "type": "object",
            "properties": {
                "max_lines": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "scrollback": {
                    "type": "string"
                },
                "user_prompt": {
                    "type": "string"
                }
            }
        },
        "webserver.TerminalAssistResponse": {
            "type": "object",
            "properties": {
                "reply": {
                    "type": "string"
                },
                "scrollback_clipped": {
                    "type": "boolean"
                }
            }
        },
        "webserver.TunnelDeleteResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "webserver.TunnelLogsResponse": {
            "type": "object",
            "properties": {
                "logs": {
                    "type": "string"
                }
            }
        },
        "webserver.TunnelStartResponse": {
            "type": "object",
            "properties": {
                "tunnel": {
                    "$ref": "#/definitions/webserver.ActiveTunnel"
                }
            }
        },
        "webserver.TunnelsListResponse": {
            "type": "object",
            "properties": {
                "tunnels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webserver.ActiveTunnel"
                    }
                }
            }
        },
        "webserver.UploadResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ui.HostExecResult"
                    }
                }
            }
        },
        "webserver.ValidateContentError": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "webserver.ValidateContentRequest": {
            "type": "object",
            "properties": {
                "recipe_content": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "webserver.ValidateContentResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webserver.ValidateContentError"
                    }
                },
                "graph": {
                    "$ref": "#/definitions/webserver.RecipeGraphPlanResponse"
                },
                "plan": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webserver.ResolvedStepSummary"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Use ` + "`" + `Authorization: Bearer \u003ctoken\u003e` + "`" + ` where ` + "`" + `\u003ctoken\u003e` + "`" + ` is the web UI token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "HoneyTokenHeader": {
            "description": "Alternative header: ` + "`" + `X-Honey-Token: \u003ctoken\u003e` + "`" + `.",
            "type": "apiKey",
            "name": "X-Honey-Token",
            "in": "header"
        },
        "TokenQuery": {
            "description": "Optional query token (same value) for URLs: ` + "`" + `?token=\u003ctoken\u003e` + "`" + `.",
            "type": "apiKey",
            "name": "token",
            "in": "query"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8765",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Honey Web API",
	Description:      "REST API for the honey web UI (`honey web`). Authenticate with the same token printed at startup, or `HONEY_WEB_TOKEN`. WebSocket endpoints `GET /ws/ssh` and `GET /ws/pve-qemu-vnc` are not described by this OpenAPI document.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
