/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Providers',
      link: {type: 'doc', id: 'providers/providers-index'},
      items: [{type: 'autogenerated', dirName: 'providers'}],
    },
    'docker-auto-discover',
    'macros',
    'web-ui',
    'cue-recipes',
    'plugins-development',
    'add-new-backend',
    'anomaly-detection',
    {
      type: 'category',
      label: 'CLI Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli'
        }
      ],
    },
  ],
};

export default sidebars;
