/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    'docker-auto-discover',
    'web-ui',
    'cue-recipes',
    'plugins-development',
    'add-new-backend',
    {
      type: 'category',
      label: 'CLI Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli'
        }
      ],
    },
  ],
};

export default sidebars;
